version: '3'

services:
  nginx:
    container_name: nginx
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 8083:80
    depends_on:
      - server
      - client
    networks:
      - nginx-network
  client:
    container_name: client
    build: ./client
    restart: always
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 14401:80
    depends_on:
      - server
    networks:
      - vue-fastapi-network
      - nginx-network
  server:
    container_name: server
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - ./server:/app
    depends_on:
      - mongodb
    networks:
      - fastapi-mongodb-network
      - vue-fastapi-network
      - nginx-network
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    command: ["--auth", "--bind_ip_all"]
    env_file:
      - ./server/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      TZ: "Asia/Bangkok"
    volumes:
      - mongo:/data/db
      - ./server/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - fastapi-mongodb-network

volumes:
  mongo:

networks:
  fastapi-mongodb-network:
  nginx-network:
  vue-fastapi-network:
